### ISSUE TITLE
Review CamelCase/snake_case use 

### ISSUE THREAD

**Issue by LCrossman** [LCrossman/microBioRust#6]
## Description

macro_rules use the fields directly from enum to create getters and setters.  However, Cargo prefers CamelCase for Enum and snake_case for getters and setters.

**Change Type:**
- [ ] Refactoring

**Current Structure:**
macro_rules getters and setters use the fields directly.  However, cargo prefers different cases for enum and getters/setters

**Proposed Changes:**
Either:
Make code changes to incorporate the cases
Or:
Decide to leave it as it is.

## Motivation

Rust case handling indicates the current situation does not follow the rules

## Potential Impact

Changing the cases requires refactoring

**Comment by Pranith2003** [comment]
Please assign me this

**Comment by LCrossman** [comment]
Fixed, just to check the docs
